image: php:7.2-cli-buster

stages:
  - deploy
before_script:
    - pwd
    - curl -LO https://deployer.org/deployer.phar
    - apt update -y && apt install -y openssh-client && apt clean
    - mkdir ~/.ssh && chmod 0700 ~/.ssh
    - cp $SSHPRIVKEY ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
    - cp $SSHPUBKEY ~/.ssh/id_rsa.pub
    - chmod 0644 ~/.ssh/id_rsa.pub
    - cp $SSHKNOWNHOSTS ~/.ssh/known_hosts
    - chmod 0644 ~/.ssh/known_hosts
    - cat ~/.ssh/known_hosts
deploy_staging:
  stage: deploy
  script:
    - script "php deployer.phar deploy staging -vvv"
